apiVersion: v1
kind: Secret
metadata:
  name: m3u-gateway-secrets
  namespace: m3u-playlist-player
type: Opaque
stringData:
  Xtream__Host: ""
  Xtream__Username: ""
  Xtream__Password: ""
  Xtream__EpgUrl: ""
