apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - gateway-secret.yaml
  - gateway.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/managed-by: argocd

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"

images:
  - name: m3u-gateway
    newName: ghcr.io/ljearypoiynt/m3u-playlist-player/gateway
    newTag: master-325556d
