apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: m3u-playlist-player
  namespace: argocd
  finalizers:
    - argoproj.io/resources-finalizer
spec:
  project: m3u-playlist-player-project

  source:
    repoURL: https://github.com/ljearypoiynt/M3U-Playlist-player.git
    targetRevision: HEAD
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: m3u-playlist-player

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /spec/volumeName
